/**
 * Benicia Tile Matcher - Tile Data
 * All 28 tiles by Guillermo Granizo along First Street, Benicia, CA
 */

const TILES = [
  {
    id: 1,
    name: "World War I",
    block: 1150,
    side: "east",
    zoneId: "zone-1",
    image: "images/tiles/01-world-war-i.jpg",
    landmark: "Veterans Memorial Hall",
    address: "1150 First Street",
    fact: "WWI revived the inactive Benicia Arsenal, transforming it into the U.S. Army's main ordnance depot on the entire West Coast.",
    hint: "This tile is at the far east end of First Street, near the Veterans Memorial.",
    learnMoreUrl: "https://beniciahistory.org/World-War-I-Tile"
  },
  {
    id: 2,
    name: "World War II",
    block: 1150,
    side: "east",
    zoneId: "zone-2",
    image: "images/tiles/02-world-war-ii.jpg",
    landmark: "Veterans Memorial Hall",
    address: "1150 First Street",
    fact: "During WWII, the Benicia Arsenal employed over 6,000 workers and became one of the largest military supply depots in the nation.",
    hint: "This tile is grouped with the other war memorials at the far east end of First Street.",
    learnMoreUrl: "https://beniciahistory.org/World-War-II-Tile"
  },
  {
    id: 3,
    name: "Korean War",
    block: 1150,
    side: "east",
    zoneId: "zone-3",
    image: "images/tiles/03-korean-war.jpg",
    landmark: "Veterans Memorial Hall",
    address: "1150 First Street",
    fact: "The Korean War era saw the Benicia Arsenal at peak operations, processing massive quantities of military equipment for the Pacific theater.",
    hint: "Look for this tile near the Veterans Memorial, grouped with the other war tiles.",
    learnMoreUrl: "https://beniciahistory.org/Korean-War-Tile"
  },
  {
    id: 4,
    name: "Vietnam War",
    block: 1150,
    side: "east",
    zoneId: "zone-4",
    image: "images/tiles/04-vietnam-war.jpg",
    landmark: "Veterans Memorial Hall",
    address: "1150 First Street",
    fact: "The Benicia Arsenal closed in 1964 during the Vietnam era, ending over a century of military operations that had defined the city.",
    hint: "This tile is at the far east end, near the Veterans Memorial with the other war tiles.",
    learnMoreUrl: "https://beniciahistory.org/Vietnam-War-Tile"
  },
  {
    id: 5,
    name: "Benicia Boy",
    block: 1000,
    side: "east",
    zoneId: "zone-5",
    image: "images/tiles/05-benicia-boy.jpg",
    landmark: "First & East J Streets",
    address: "First & East J Streets",
    fact: "John Heenan, 'The Benicia Boy,' fought in what's considered the first international boxing championship in 1860 \u2014 42 brutal rounds ending in a draw.",
    hint: "This tile is on the east side, in the 1000 block near J Street.",
    learnMoreUrl: "https://beniciahistory.org/benicia-boy-tile"
  },
  {
    id: 6,
    name: "St. Paul's",
    block: 900,
    side: "east",
    zoneId: "zone-6",
    image: "images/tiles/06-st-pauls.jpg",
    landmark: "120 East J Street",
    address: "First & East J Street",
    fact: "St. Paul's rectory is a Connecticut saltbox house built in 1790, shipped in pieces around Cape Horn, and reassembled in Benicia in 1868.",
    hint: "This tile is on the east side, in the 900 block area.",
    learnMoreUrl: "https://beniciahistory.org/St-Pauls-Tile"
  },
  {
    id: 7,
    name: "Concepci\u00f3n",
    block: 900,
    side: "east",
    zoneId: "zone-7",
    image: "images/tiles/07-concepcion.jpg",
    landmark: "Olson Realty",
    address: "920 First Street",
    fact: "Concepci\u00f3n Arguello fell in love with a Russian count at age 15. He died seeking permission to marry her, and she became California's first native-born nun.",
    hint: "This tile is on the east side, in the 900 block.",
    learnMoreUrl: "https://beniciahistory.org/Concepcion-Tile"
  },
  {
    id: 8,
    name: "Benicia Collegiate Institute",
    block: 900,
    side: "east",
    zoneId: "zone-8",
    image: "images/tiles/08-collegiate-institute.jpg",
    landmark: "Coldwell Banker",
    address: "900 First Street",
    fact: "Founded in 1855, this school became California's first law school by 1858, helping earn Benicia the title 'Athens of California.'",
    hint: "This tile is on the east side, in the 900 block.",
    learnMoreUrl: "https://beniciahistory.org/Benicia-Collegiate-Institute-Tile"
  },
  {
    id: 9,
    name: "Young Ladies Seminary",
    block: 800,
    side: "east",
    zoneId: "zone-9",
    image: "images/tiles/09-young-ladies-seminary.jpg",
    landmark: "Pure Hair Studios",
    address: "838 First Street",
    fact: "California's first girls' school later became Mills College in Oakland. Tuition was $200 per semester \u2014 a fortune in the 1850s.",
    hint: "This tile is on the east side, in the 800 block.",
    learnMoreUrl: "https://beniciahistory.org/Young-Ladies-Seminary-Tile"
  },
  {
    id: 10,
    name: "The Great Barge Fight",
    block: 800,
    side: "east",
    zoneId: "zone-10",
    image: "images/tiles/10-great-barge-fight.jpg",
    landmark: "800 Block East",
    address: "800 Block First Street",
    fact: "This tile commemorates one of Benicia's most colorful episodes \u2014 a waterfront brawl that became local legend along the Carquinez Strait.",
    hint: "This tile is on the east side, in the 800 block.",
    learnMoreUrl: "https://beniciahistory.org/First-Street-Tiles"
  },
  {
    id: 11,
    name: "Guard House",
    block: 800,
    side: "east",
    zoneId: "zone-11",
    image: "images/tiles/11-guard-house.jpg",
    landmark: "First & East H Street",
    address: "First & East H Street",
    fact: "Built in 1872, the Guard House had an elaborate ventilation system because its jail cells had no windows \u2014 including a dreaded 'dark cell.'",
    hint: "This tile is on the east side, in the 800 block near H Street.",
    learnMoreUrl: "https://beniciahistory.org/Guard-House-Tile"
  },
  {
    id: 12,
    name: "Pacific Mail",
    block: 700,
    side: "east",
    zoneId: "zone-12",
    image: "images/tiles/12-pacific-mail.jpg",
    landmark: "736 First Street",
    address: "736 First Street",
    fact: "Pacific Mail's Benicia facility was the first heavy industry west of the Mississippi, with a 50-ton crane and over 2,000 workers at its peak.",
    hint: "This tile is on the east side, in the 700 block.",
    learnMoreUrl: "https://beniciahistory.org/Pacific-Mail-Tile"
  },
  {
    id: 13,
    name: "Congregational Church",
    block: 700,
    side: "east",
    zoneId: "zone-13",
    image: "images/tiles/13-congregational-church.jpg",
    landmark: "Forever Sala Thai",
    address: "718 First Street",
    fact: "This congregation created Benicia's first free reading room in 1893 \u2014 the forerunner of the Benicia Public Library.",
    hint: "This tile is on the east side, in the 700 block.",
    learnMoreUrl: "https://beniciahistory.org/Congregational-Church-Tile"
  },
  {
    id: 14,
    name: "Jack London",
    block: 700,
    side: "east",
    zoneId: "zone-14",
    image: "images/tiles/14-jack-london.jpg",
    landmark: "Majestic Caf\u00e9",
    address: "700 First Street",
    fact: "At age 16, Jack London bought a sloop called the Razzle Dazzle and became an oyster pirate before turning lawman as a Fish Patrol deputy.",
    hint: "This tile is on the east side, in the 700 block.",
    learnMoreUrl: "https://beniciahistory.org/jack-london-tile"
  },
  {
    id: 15,
    name: "St. Dominic's",
    block: 600,
    side: "east",
    zoneId: "zone-15",
    image: "images/tiles/15-st-dominics.jpg",
    landmark: "Sandoval's",
    address: "640 First Street",
    fact: "St. Dominic's is the Mother Church of Solano County's Catholics, established in 1854 by Dominican friars from Monterey.",
    hint: "This tile is on the east side, in the 600 block \u2014 the westernmost east-side tile.",
    learnMoreUrl: "https://beniciahistory.org/st-dominics-tile"
  },
  {
    id: 16,
    name: "Semple & Larkin",
    block: 600,
    side: "west",
    zoneId: "zone-16",
    image: "images/tiles/16-semple-larkin.jpg",
    landmark: "Dianna's Bakery & Caf\u00e9",
    address: "639 First Street",
    fact: "Robert Semple stood 6'7\" tall and was a dentist, printer, soldier, and publisher. He founded California's first newspaper and co-founded Benicia.",
    hint: "This tile is on the west side, in the 600 block \u2014 the westernmost west-side tile.",
    learnMoreUrl: "https://beniciahistory.org/semple-and-larkin-tile"
  },
  {
    id: 17,
    name: "Granizo's Art & Benicia's History",
    block: 650,
    side: "west",
    zoneId: "zone-17",
    image: "images/tiles/17-granizos-art.jpg",
    landmark: "State Capitol",
    address: "115 West G Street",
    fact: "This 28th tile was added years after the original 27, funded by a bequest from retired city employee Lee Syracuse. Artist Granizo was born William Wagner.",
    hint: "This tile is near West G Street, close to the State Capitol building.",
    learnMoreUrl: "https://beniciahistory.org/granizos-art-and-benicias-history-tile"
  },
  {
    id: 18,
    name: "State Capitol",
    block: 700,
    side: "west",
    zoneId: "zone-18",
    image: "images/tiles/18-state-capitol.jpg",
    landmark: "First & West G Streets",
    address: "First & West G Streets",
    fact: "Benicia served as California's capital for just 13 months (1853\u20131854). Its Capitol is the only surviving early California statehouse.",
    hint: "This tile is on the west side, in the 700 block near G Street.",
    learnMoreUrl: "https://beniciahistory.org/state-capitol-tile"
  },
  {
    id: 19,
    name: "Benicia Firefighters",
    block: 700,
    side: "west",
    zoneId: "zone-19",
    image: "images/tiles/19-benicia-firefighters.jpg",
    landmark: "First & West H Street Alley",
    address: "First & West H Street",
    fact: "Benicia's volunteer fire brigade, founded in 1847, is California's oldest continuous firefighting service. Their Phoenix Engine dates to the 1820s.",
    hint: "This tile is on the west side, in the 700 block.",
    learnMoreUrl: "https://beniciahistory.org/Benicia-Firefighters-Tile"
  },
  {
    id: 20,
    name: "Bella Union",
    block: 700,
    side: "west",
    zoneId: "zone-20",
    image: "images/tiles/20-bella-union.jpg",
    landmark: "State Farm building",
    address: "739 First Street",
    fact: "During Prohibition, there was a secret underground saloon beneath the southwest corner of First and H Streets \u2014 right where this tile stands.",
    hint: "This tile is on the west side, in the 700 block.",
    learnMoreUrl: "https://beniciahistory.org/bella-union-tile"
  },
  {
    id: 21,
    name: "The Solano",
    block: 800,
    side: "west",
    zoneId: "zone-21",
    image: "images/tiles/21-the-solano.jpg",
    landmark: "Prudential California",
    address: "801 First Street",
    fact: "When launched in 1879, the Solano was the world's largest ferry \u2014 carrying two full trains across the Carquinez Strait in just 9 minutes.",
    hint: "This tile is on the west side, in the 800 block.",
    learnMoreUrl: "https://beniciahistory.org/the-solano-tile"
  },
  {
    id: 22,
    name: "Do\u00f1a Francisca Vallejo",
    block: 800,
    side: "east",
    zoneId: "zone-22",
    image: "images/tiles/22-dona-vallejo.jpg",
    landmark: "800 Block East",
    address: "800 Block First Street",
    fact: "The city of Benicia is named after Francisca Benicia de Vallejo, wife of General Mariano Vallejo, one of the city's three founding fathers.",
    hint: "This tile is on the east side, in the 800 block.",
    learnMoreUrl: "https://beniciahistory.org/First-Street-Tiles"
  },
  {
    id: 23,
    name: "Captain Walsh's Home",
    block: 800,
    side: "west",
    zoneId: "zone-23",
    image: "images/tiles/23-captain-walshs-home.jpg",
    landmark: "First & West I Street",
    address: "First & West I Street",
    fact: "This Gothic Revival cottage was built on the East Coast, shipped in pieces around Cape Horn, and reassembled in Benicia before December 1850.",
    hint: "This tile is on the west side, in the 800 block.",
    learnMoreUrl: "https://beniciahistory.org/captain-walshs-home-tile"
  },
  {
    id: 24,
    name: "Cherish Our Past",
    block: 900,
    side: "west",
    zoneId: "zone-24",
    image: "images/tiles/24-cherish-our-past.jpg",
    landmark: "The ELEVaTE Company",
    address: "901 First Street",
    fact: "Local legend says the discovery of gold at Sutter's Mill was first revealed at Von Pfister's store in Benicia, inspiring some of the very first 49ers.",
    hint: "This tile is on the west side, in the 900 block.",
    learnMoreUrl: "https://beniciahistory.org/cherish-our-past-and-embrace-our-future-tile"
  },
  {
    id: 25,
    name: "Benicia Barracks",
    block: 900,
    side: "west",
    zoneId: "zone-25",
    image: "images/tiles/25-benicia-barracks.jpg",
    landmark: "Antiques on First",
    address: "919 First Street",
    fact: "The Benicia Barracks spanned 992 acres and most buildings were pre-built on the East Coast and shipped around Cape Horn for assembly.",
    hint: "This tile is on the west side, in the 900 block.",
    learnMoreUrl: "https://beniciahistory.org/benicia-barracks-tile"
  },
  {
    id: 26,
    name: "Masonic Temple",
    block: 900,
    side: "west",
    zoneId: "zone-26",
    image: "images/tiles/26-masonic-temple.jpg",
    landmark: "Collektive Boutique",
    address: "935 First Street",
    fact: "California's first Masonic Temple was built here in 1850 for $18,000. Robert Semple donated the lumber and Alexander Riddell the land.",
    hint: "This tile is on the west side, in the 900 block.",
    learnMoreUrl: "https://beniciahistory.org/masonic-temple-tile"
  },
  {
    id: 27,
    name: "Commandant's Home",
    block: 1000,
    side: "west",
    zoneId: "zone-27",
    image: "images/tiles/27-commandants-home.jpg",
    landmark: "1000 Block West",
    address: "1000 Block First Street",
    fact: "The Commandant's Home served as the residence for the commanding officer of the Benicia Arsenal, overlooking the strategic Carquinez Strait.",
    hint: "This tile is on the west side, in the 1000 block.",
    learnMoreUrl: "https://beniciahistory.org/First-Street-Tiles"
  },
  {
    id: 28,
    name: "Clock Tower",
    block: 1000,
    side: "west",
    zoneId: "zone-28",
    image: "images/tiles/28-clock-tower.jpg",
    landmark: "1189 Washington Street",
    address: "1189 Washington Street",
    fact: "Originally a 3-story Arsenal storehouse from 1859, a 1912 fire destroyed its interior. The restored 2-story Clock Tower now hosts community events.",
    hint: "This tile is on the west side, in the 1000 block \u2014 at the far east end.",
    learnMoreUrl: "https://beniciahistory.org/Clock-Tower-Tile"
  }
];
