<?php
# Benicia Historic Homes Wiki - LocalSettings.php
# This file is mounted into the MediaWiki container via docker-compose.yml.
# It is generated by the installer and then customized for this project.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "db";
$wgDBname = getenv('MEDIAWIKI_DB_NAME') ?: "benicia_wiki";
$wgDBuser = getenv('MEDIAWIKI_DB_USER') ?: "wiki";
$wgDBpassword = getenv('MEDIAWIKI_DB_PASSWORD') ?: "";
$wgDBprefix = "";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Site settings
$wgSitename = "Benicia Historic Homes Wiki";
$wgMetaNamespace = "Benicia_Historic_Homes_Wiki";
$wgServer = "http://64.23.211.225:8080";
$wgScriptPath = "";
$wgArticlePath = "/wiki/$1";

## Secret key - CHANGE THIS in production
$wgSecretKey = "a3439373f6aba9e0d28e9c5b7bb8c1f9e73134016858312e95f4920a1d9451a1";
$wgUpgradeKey = "3d52ba4acf739e9e";

## Paths
$wgStylePath = "$wgScriptPath/skins";
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## Skin
wfLoadSkin( 'Vector' );
$wgDefaultSkin = "vector";

## File uploads
$wgEnableUploads = true;
$wgFileExtensions = array_merge(
    $wgFileExtensions,
    [ 'pdf', 'svg', 'tif', 'tiff', 'webp' ]
);
$wgMaxUploadSize = 50 * 1024 * 1024; // 50 MB

## Rights - allow anyone to read, require login to edit
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['upload'] = true;

## Short URLs
$wgUsePathInfo = true;

## Email (disabled for local dev)
$wgEnableEmail = false;

## Caching
$wgMainCacheType = CACHE_ACCEL;
$wgCacheDirectory = "$IP/cache";

## Extensions

# ParserFunctions (bundled)
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;

# Cite (bundled)
wfLoadExtension( 'Cite' );

# CategoryTree (bundled)
wfLoadExtension( 'CategoryTree' );

# Semantic MediaWiki
wfLoadExtension( 'SemanticMediaWiki' );
enableSemantics( 'localhost' );

# Semantic MediaWiki settings
$smwgDefaultStore = 'SMWSQLStore3';
$smwgEnabledEditPageHelp = false;
$smwgQMaxInlineLimit = 500;

# Page Forms
wfLoadExtension( 'PageForms' );

# Semantic Result Formats
wfLoadExtension( 'SemanticResultFormats' );

# Maps extension
wfLoadExtension( 'Maps' );
$egMapsDefaultService = 'leaflet';

## Debug settings (disable in production)
# $wgShowExceptionDetails = true;
# $wgShowDBErrorBacktrace = true;
# $wgDebugToolbar = true;

## Job queue
$wgJobRunRate = 0.5;
